### ISSUE TITLE
issue with using using fullscreen on multiple maps 

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#10]
I implemented Leaflet.fullscreen in my WordPress mapping plugin www.mapsmarker.com. A user now reported that there is an issue when multiple maps are present on one page - only the first one is working correctly when clicking the fullscreen button; on all other maps, the map tiles only gets loaded partially.
His maps can be found at http://www.diekracks.org/karten/

I tried to find the issue for this but failed. Any idea, what could be causing this?
Thx for any help!
Robert

**Comment by jfirebaugh** [comment]
This is very likely to be the same issue as https://github.com/Leaflet/Leaflet/issues/1980, so it will be fixed with Leaflet 0.7. You can verify that by testing with [Leaflet 0.7-dev](http://leafletjs.com/download.html).

**Comment by seyfro** [comment]
thanks - just tested my maps with 0.7-dev and this issues is solved.

**Comment by lothan** [comment]
I seem to be having this same problem with the current versions of leaflet and leaflet fullscreen. An example is at https://latentculture.com/transfiguration-ii/

The issue is entirely with the second map. Not only is the map size not updated when going into fullscreen mode, but when in fullscreen the button to return doesn't work. I've been working on a fix but don't know much of this codebase so I thought I would reach out.

**Comment by lothan** [comment]
Just a small update after a couple hours of debugging. The main issue is that when _onFullscreenChange is called, `this` is set to the first map, not the second one. Also, the line `if (e.target != this.getContainer())
            return; ` is not in my version of leaflet fullscreen (from the fix [cited here](https://github.com/Leaflet/Leaflet.fullscreen/commit/259ac31aec8bdac184df64d9056c41b269e74547))
But readding doesn't fix anything. I'm no expert in JS, anyone have any ideas on how to fix? Or am I just making a stupid error in my implementation?
